### ISSUE TITLE
Error: HACKRF_ERROR_LIBUSB (-1000) 

### ISSUE THREAD

**Issue by stackprogramer** [mossmann/hackrf#305] opened 2017-01-24 14:55 UTC
hi, i have debian 8, when i connect the hackrf and i type hackrf_info it retruens this as root.
my debian  is in wmware, i can work it with windows in sdrshrp.
i even tested solution of this link it not fixed...............
https://github.com/mossmann/hackrf/issues/165
> Found HackRF board 0:
Board ID Number: 2 (HackRF One)
Firmware Version: git-7e81647
Part ID Number: 0xa000cb3c 0x00534f4b
Serial Number: 0x00000000 0x00000000 0x406464c8 0x23846d4b
hackrf_get_operacake_boards() failed: HACKRF_ERROR_LIBUSB (-1000)

when i typed hackrf in not super user it return:

> sp@debian:~$ hackrf_info
Found HackRF board 0:
hackrf_open() failed: HACKRF_ERROR_LIBUSB (-1000)

**Comment by SonnyRajagopalan** [comment] 2017-01-24 15:09
Try the solution in Issue #301

**Comment by dominicgs** [comment] 2017-01-24 16:16
There are two separate issues here:
1) The `hackrf_get_operacake_boards() failed: HACKRF_ERROR_LIBUSB (-1000)` message.  This is a duplicate of issue #304 and I will fix it in the next hour.

2) Unable to access the board as non-root user.  This is a permission issue.  There is a udev rule that gets installed as part of the HackRF host code install process.  It defaults to plugdev group but also supports the usb group.  Check which of these groups exist on your system, then look for `/etc/udev/rules.d/53-hackrf.rules`, check that it references the appropriate group and that you are a member of that group.

**Comment by stackprogramer** [comment] 2017-01-26 11:07
yet i have  `error  hackrf_get_operacake_boards() failed: HACKRF_ERROR_LIBUSB (-1000)`

**Comment by stackprogramer** [comment] 2017-01-26 12:52
finally for not any response i used commit 6b831d31cc15c323ba035183ff425b3980a9378c.
https://github.com/mossmann/hackrf/commit/6b831d31cc15c323ba035183ff425b3980a9378c
now every hackrf_info has good response 
best regards stackprogramer

**Comment by dominicgs** [comment] 2017-01-26 16:34
I'm sorry, I commented on issue #304 but didn't update this one.  As long as your firmware matches the host code version, this error will not occur.

@stackprogramer Did you solve the non-root user access to the HackRF?

**Comment by stackprogramer** [comment] 2017-01-27 06:05
@dominicgs  your welcome, thanks,non-root user access is not solved  yet.but important is for me is working. that works in as root.
best regards stackprogramer

**Closed** 2017-11-17 02:20 UTC
Labels: technical support
