### ISSUE TITLE
Shorted burned up an ic on the board using an amplifier

### ISSUE THREAD

**Issue by alexxmarsh44** [mossmann/hackrf#776] opened 2020-08-18 19:08 UTC
I plugged an LNA amplifier into the antenna port it and it immedietly smoked and i think I identified the ic that burned up. 

![hackrf](https://user-images.githubusercontent.com/59932969/90554667-11768c00-e14b-11ea-945d-86fb14095c41.JPG)

Which part is this?  I want to attempt to replace it.  Do you think its possible that it is an isolated part that burned up or are their other likely ones that went with it?

**Comment by cjheath** [comment] 2020-09-06 10:29
This is the MOSFET switch for the bias T that feeds power to the external LNA.
You will damage it if the antenna port is short circuit or draws too much power.

**Comment by miek** [comment] 2020-09-10 15:01
I think this could also be caused by the LNA feeding back a high enough bias voltage on to the antenna port, if it was an externally powered LNA?
It's hard to tell if that's the only failed part, a good test would be to de-solder it and then check functionality.

**Comment by cjheath** [comment] 2020-09-10 23:09
If you don't use the Bias T, the whole HackRF performance can be improved by removing the inductor (just bottom-left of the red square). It loads the antenna port unnecessarily if you don't need it. I tried to improve the Bias T by adding a second stage (smaller inductor) but don't yet have measurements on how successful it was.

**Comment by alexxmarsh44** [comment] 2020-09-18 11:28
I now got it working temporarily as it turns on again.  As soon as I use it in gnuradio to receive it starts blinking the 3v3 1v8 rf and usb lights continuously at the same time.  It gives a shorted error in gnuradio at the same time.  It only works for maybe twenty seconds.  If I attempt to use it for something less strenuous it will start flashing but before it does I noticed the board getting very hot much hotter than usual.  Any ideas on how to fix it?  Ill try anything before chocking it up to a loss.

**Comment by cjheath** [comment] 2020-09-18 23:35
@alexxmarsh44 Even if you can't replace the MOSFET, you can remove it with wire clippers. This should restore normal function of the HackRF, but you won't be able to power an external LNA.

**Comment by mossmann** [comment] 2021-01-24 00:56
Are you still looking for help with this problem? We will close the issue if we don't see a reply within the next month.

**Comment by straithe** [comment] 2021-02-23 21:42
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.

**Closed by straithe** 2021-02-23 21:42 UTC
Labels: hardware, technical support
