### ISSUE TITLE
Could I use two or more hackrf ones with one host at the same time?

### ISSUE THREAD

**Issue by franklinzhang** [mossmann/hackrf#175] opened 2015-05-08 01:13 UTC
I've tried in my computer(os: ubuntu 14.04) but failed.

**Comment by dominicgs** [comment] 2015-05-08 10:49
This feature has been implemented but is, as yet, untested and therefore has not been released.  The code for it is contained in theis pull request: https://github.com/mossmann/hackrf/pull/158

If you would like to use it, I would recommend that you try that version of the host software.  Feedback on how it works for you would be very welcome.

**Comment by kpansky** [comment] 2015-05-08 13:11
I have been running with #158 applied for some time now, and it works very well.  I have not gone through the effort of building and testing the updated GNU radio osmosdr driver using the updated libhackrf, but the updated command line tools/libhackrf/LPC firmware seem to work well at least.

It would be great to get #158 merged and released along with the hessu/gr-osmosdr updates.

**Comment by dominicgs** [comment] 2015-05-11 17:14
Closing this issue as it is addressed by pull request #158 and is a duplicate of issue #87.

**Closed by dominicgs** 2015-05-11 17:14 UTC
