### ISSUE TITLE
HackRF Protocol / Interface Specifications Document

### ISSUE THREAD

**Issue by anisjamil345** [mossmann/hackrf#652] opened 2019-10-17 08:21 UTC
I want to emulate HackRF against Simon's "SDR Console" through LabVIEW  for which I need HackRF Protocol / Interface Specifications Document. From where can I get this document clearly defining the communication protocol implemented.
   Regards

**Comment by miek** [comment] 2019-11-25 19:22
Duplicate of #647

**Closed by miek** 2019-11-25 19:22 UTC
Labels: duplicate
