### ISSUE TITLE
Receive error using GNU Radio

### ISSUE THREAD

**Issue by WilliamMailhot** [mossmann/hackrf#392] opened 2017-07-09 04:27 UTC
### Steps to reproduce
1. Make a flowgraph in GNU radio with a FFT sink
2. Execute flow graph
3. Kill flow graph using kill flowgraph button

### Expected behaviour
RX light should stop being enabled on the HackRF

### Actual behaviour
RX light stays ON until reset or power off

Side note: if I exit the FFT flowgraph using it's GUI exit button "X" the RX light turns off

### Version information
**Operating system**:
Pentoo 4.4.8

++ Not sure if it is an error with GNU Radio or firmware ++
++ Did not try using other firmware updates yet ++

**Comment by dominicgs** [comment] 2017-07-11 15:06
This is relatively common, there is a bug somewhere that means that we don't cleanly shut down the HackRF when using the kill flowgraph button.  I haven't been able to track it down so far.

I recommend using the GUI's 'X' button as a workaround.

**Comment by miek** [comment] 2019-12-09 12:26
Duplicate of #180

**Closed by miek** 2019-12-09 12:26 UTC
Labels: bug
